"""
补充种子数据：其他主流机器人厂商的产品数据（静态）
包含：Figure AI、1X Technologies、Fourier Intelligence、优必选、小米、
      Universal Robots、Franka Emika、Doosan Robotics、Yaskawa Motoman、
      Kawasaki Robotics、Techman Robot、AUBO、Hanson Robotics、
      Engineered Arts、Pudu Robotics、Keenon Robotics、
      AgileX Robotics、Clearpath Robotics、MiR、Fetch Robotics、
      Rethink Robotics、Bear Robotics、Apptronik、Sanctuary AI 等
"""
from .base import BaseSpider


class AdditionalSeedsSpider(BaseSpider):
    name = "additional_seeds"
    manufacturer_name = ""
    manufacturer_name_en = ""
    manufacturer_country = ""
    manufacturer_country_code = ""
    manufacturer_website = ""

    # 额外的多厂商种子数据，格式：(厂商信息, 产品列表)
    SEED_DATA = [
        # ── 人形机器人：美国/海外 ──────────────────────────────────
        (
            {
                "name": "Figure AI",
                "name_en": "Figure AI",
                "country": "美国",
                "country_code": "US",
                "website_url": "https://figure.ai",
                "description": None,
            },
            [
                {
                    "name": "Figure 02",
                    "name_en": "Figure 02",
                    "description": "通用人形机器人，搭载多模态 AI，可在工厂执行复杂装配任务，已与宝马合作部署",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "人形机器人",
                    "category_en": "Humanoid Robot",
                    "price_range": "inquiry",
                    "status": "active",
                }
            ],
        ),
        (
            {
                "name": "1X Technologies",
                "name_en": "1X Technologies",
                "country": "挪威",
                "country_code": "NO",
                "website_url": "https://www.1x.tech",
                "description": None,
            },
            [
                {
                    "name": "NEO",
                    "name_en": "NEO",
                    "description": "家庭服务人形机器人，双足行走，具备灵巧操作能力，面向家庭消费市场",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "人形机器人",
                    "category_en": "Humanoid Robot",
                    "price_range": "inquiry",
                    "status": "upcoming",
                },
                {
                    "name": "EVE",
                    "name_en": "EVE",
                    "description": "轮式人形机器人，专注于工业与商业场所的辅助作业",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "人形机器人",
                    "category_en": "Humanoid Robot",
                    "price_range": "inquiry",
                    "status": "active",
                },
            ],
        ),
        (
            {
                "name": "Apptronik",
                "name_en": "Apptronik",
                "country": "美国",
                "country_code": "US",
                "website_url": "https://apptronik.com",
                "description": None,
            },
            [
                {
                    "name": "Apollo",
                    "name_en": "Apollo",
                    "description": "Apptronik 人形机器人，身高 1.73m，有效载荷 55kg，面向工业物流设计，已与梅赛德斯-奔驰合作",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "人形机器人",
                    "category_en": "Humanoid Robot",
                    "price_range": "inquiry",
                    "status": "active",
                }
            ],
        ),
        (
            {
                "name": "Sanctuary AI",
                "name_en": "Sanctuary AI",
                "country": "加拿大",
                "country_code": "CA",
                "website_url": "https://sanctuary.ai",
                "description": None,
            },
            [
                {
                    "name": "Phoenix",
                    "name_en": "Phoenix",
                    "description": "Sanctuary AI 人形机器人，搭载 Carbon AI 系统，模仿人类认知与操作能力，已在零售业试点部署",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "人形机器人",
                    "category_en": "Humanoid Robot",
                    "price_range": "inquiry",
                    "status": "active",
                }
            ],
        ),
        (
            {
                "name": "Neura Robotics",
                "name_en": "Neura Robotics",
                "country": "德国",
                "country_code": "DE",
                "website_url": "https://neura-robotics.com",
                "description": None,
            },
            [
                {
                    "name": "4NE-1",
                    "name_en": "4NE-1",
                    "description": "Neura Robotics 认知人形机器人，具备视觉、触觉与语音交互能力，定位为家庭与办公室助手",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "人形机器人",
                    "category_en": "Humanoid Robot",
                    "price_range": "inquiry",
                    "status": "upcoming",
                }
            ],
        ),
        # ── 中国人形 ──────────────────────────────────────────────
        (
            {
                "name": "傅利叶智能",
                "name_en": "Fourier Intelligence",
                "country": "中国",
                "country_code": "CN",
                "website_url": "https://www.fftai.com",
                "description": None,
            },
            [
                {
                    "name": "GR-1",
                    "name_en": "GR-1",
                    "description": "通用人形机器人，身高 1.65m，具备行走、搬运与上下楼梯能力",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "人形机器人",
                    "category_en": "Humanoid Robot",
                    "price_range": "inquiry",
                    "status": "active",
                },
                {
                    "name": "GR-2",
                    "name_en": "GR-2",
                    "description": "傅利叶第二代通用人形机器人，具备更强大的全身运动控制与灵巧手操作能力",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "人形机器人",
                    "category_en": "Humanoid Robot",
                    "price_range": "inquiry",
                    "status": "active",
                },
            ],
        ),
        (
            {
                "name": "优必选科技",
                "name_en": "UBTECH Robotics",
                "country": "中国",
                "country_code": "CN",
                "website_url": "https://www.ubtrobot.com",
                "description": None,
            },
            [
                {
                    "name": "Walker S",
                    "name_en": "Walker S",
                    "description": "工业人形机器人，已进入新能源汽车工厂进行质检作业",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "人形机器人",
                    "category_en": "Humanoid Robot",
                    "price_range": "inquiry",
                    "status": "active",
                },
                {
                    "name": "Walker X",
                    "name_en": "Walker X",
                    "description": "优必选消费级人形机器人，26 个智能伺服关节，支持自然语言交互与家庭服务场景",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "人形机器人",
                    "category_en": "Humanoid Robot",
                    "price_range": "high",
                    "status": "active",
                },
            ],
        ),
        (
            {
                "name": "小米",
                "name_en": "Xiaomi",
                "country": "中国",
                "country_code": "CN",
                "website_url": "https://www.mi.com",
                "description": None,
            },
            [
                {
                    "name": "CyberOne",
                    "name_en": "CyberOne",
                    "description": "小米全尺寸人形机器人，身高 177cm，具备情感识别与语音交互能力",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "人形机器人",
                    "category_en": "Humanoid Robot",
                    "price_range": "inquiry",
                    "status": "active",
                }
            ],
        ),
        (
            {
                "name": "Tesla",
                "name_en": "Tesla",
                "country": "美国",
                "country_code": "US",
                "website_url": "https://www.tesla.com",
                "description": None,
            },
            [
                {
                    "name": "Optimus Gen 2",
                    "name_en": "Optimus Gen 2",
                    "description": "特斯拉人形机器人第二代，具备灵巧手，可执行鸡蛋抓取等精细操作，已在工厂内自主运行",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "人形机器人",
                    "category_en": "Humanoid Robot",
                    "price_range": "inquiry",
                    "status": "upcoming",
                }
            ],
        ),
        # ── 协作机器人 ─────────────────────────────────────────────
        (
            {
                "name": "优傲机器人",
                "name_en": "Universal Robots",
                "country": "丹麦",
                "country_code": "DK",
                "website_url": "https://www.universal-robots.com",
                "description": None,
            },
            [
                {
                    "name": "UR3e",
                    "name_en": "Universal Robots UR3e",
                    "description": "桌面型协作机器人，有效载荷 3kg，工作范围 500mm，360° 旋转末端，适用于精密装配与电子测试",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "协作机器人",
                    "category_en": "Collaborative Robot",
                    "price_range": "medium",
                    "status": "active",
                },
                {
                    "name": "UR5e",
                    "name_en": "Universal Robots UR5e",
                    "description": "Universal Robots 中型协作机器人，有效载荷 5kg，工作范围 850mm，内置力矩传感器",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "协作机器人",
                    "category_en": "Collaborative Robot",
                    "price_range": "medium",
                    "status": "active",
                },
                {
                    "name": "UR10e",
                    "name_en": "Universal Robots UR10e",
                    "description": "Universal Robots 大型协作机器人，有效载荷 12.5kg，工作范围 1300mm，适用于搬运与机器管理",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "协作机器人",
                    "category_en": "Collaborative Robot",
                    "price_range": "medium",
                    "status": "active",
                },
                {
                    "name": "UR16e",
                    "name_en": "Universal Robots UR16e",
                    "description": "Universal Robots 重载协作机器人，有效载荷 16kg，工作范围 900mm，适用于重型装配与测试",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "协作机器人",
                    "category_en": "Collaborative Robot",
                    "price_range": "medium",
                    "status": "active",
                },
                {
                    "name": "UR20",
                    "name_en": "Universal Robots UR20",
                    "description": "Universal Robots 新一代大型协作机器人，有效载荷 20kg，工作范围 1750mm，速度提升 65%",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "协作机器人",
                    "category_en": "Collaborative Robot",
                    "price_range": "high",
                    "status": "active",
                },
                {
                    "name": "UR30",
                    "name_en": "Universal Robots UR30",
                    "description": "Universal Robots 最大载荷协作机器人，有效载荷 30kg，工作范围 1300mm，适用于重型机器管理",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "协作机器人",
                    "category_en": "Collaborative Robot",
                    "price_range": "high",
                    "status": "active",
                },
            ],
        ),
        (
            {
                "name": "Franka Emika",
                "name_en": "Franka Emika",
                "country": "德国",
                "country_code": "DE",
                "website_url": "https://franka.de",
                "description": None,
            },
            [
                {
                    "name": "Franka Research 3",
                    "name_en": "Franka Research 3",
                    "description": "Franka Emika 科研协作机器人，7 轴冗余，每个关节力控，广泛应用于全球机器人操控研究",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "协作机器人",
                    "category_en": "Collaborative Robot",
                    "price_range": "high",
                    "status": "active",
                },
                {
                    "name": "Franka Production 3",
                    "name_en": "Franka Production 3",
                    "description": "Franka Emika 工业版协作机器人，有效载荷 3kg，适用于精密装配、测试与质量检测",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "协作机器人",
                    "category_en": "Collaborative Robot",
                    "price_range": "high",
                    "status": "active",
                },
            ],
        ),
        (
            {
                "name": "斗山机器人",
                "name_en": "Doosan Robotics",
                "country": "韩国",
                "country_code": "KR",
                "website_url": "https://www.doosanrobotics.com",
                "description": None,
            },
            [
                {
                    "name": "Doosan M0609",
                    "name_en": "Doosan M0609",
                    "description": "斗山协作机器人，有效载荷 6kg，工作范围 900mm，支持直接示教，适用于装配与电子制造",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "协作机器人",
                    "category_en": "Collaborative Robot",
                    "price_range": "medium",
                    "status": "active",
                },
                {
                    "name": "Doosan H2515",
                    "name_en": "Doosan H2515",
                    "description": "斗山重载协作机器人，有效载荷 25kg，工作范围 1500mm，适用于汽车零部件装配与搬运",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "协作机器人",
                    "category_en": "Collaborative Robot",
                    "price_range": "high",
                    "status": "active",
                },
                {
                    "name": "Doosan A0509",
                    "name_en": "Doosan A0509",
                    "description": "斗山轻量级协作机器人，有效载荷 5kg，一体化设计，快速部署，适用于中小企业自动化",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "协作机器人",
                    "category_en": "Collaborative Robot",
                    "price_range": "medium",
                    "status": "active",
                },
            ],
        ),
        (
            {
                "name": "安川电机",
                "name_en": "Yaskawa Motoman",
                "country": "日本",
                "country_code": "JP",
                "website_url": "https://www.motoman.com",
                "description": None,
            },
            [
                {
                    "name": "HC10DTP",
                    "name_en": "Yaskawa HC10DTP",
                    "description": "安川人机协作机器人，有效载荷 10kg，内置接触检测，无需安全护栏即可与人并肩工作",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "协作机器人",
                    "category_en": "Collaborative Robot",
                    "price_range": "high",
                    "status": "active",
                },
                {
                    "name": "GP8",
                    "name_en": "Yaskawa GP8",
                    "description": "安川高速工业机械臂，有效载荷 8kg，工作范围 727mm，速度与精度领先，适用于电子与医疗制造",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "工业机器人",
                    "category_en": "Industrial Robot",
                    "price_range": "high",
                    "status": "active",
                },
                {
                    "name": "SIA10F",
                    "name_en": "Yaskawa SIA10F",
                    "description": "安川 7 轴单臂协作机器人，外形酷似人臂，可在人机共存环境中执行复杂装配任务",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "协作机器人",
                    "category_en": "Collaborative Robot",
                    "price_range": "high",
                    "status": "active",
                },
            ],
        ),
        (
            {
                "name": "JAKA Robotics 节卡机器人",
                "name_en": "JAKA Robotics",
                "country": "中国",
                "country_code": "CN",
                "website_url": "https://www.jakarobotics.com",
                "description": None,
            },
            [
                {
                    "name": "JAKA Zu 3",
                    "name_en": "JAKA Zu 3",
                    "description": "节卡协作机器人，有效载荷 3kg，一体化设计，支持直接示教与移动 App 编程，快速部署",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "协作机器人",
                    "category_en": "Collaborative Robot",
                    "price_range": "medium",
                    "status": "active",
                },
                {
                    "name": "JAKA Zu 12",
                    "name_en": "JAKA Zu 12",
                    "description": "节卡中型协作机器人，有效载荷 12kg，工作范围 1327mm，适用于搬运、码垛与质检",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "协作机器人",
                    "category_en": "Collaborative Robot",
                    "price_range": "medium",
                    "status": "active",
                },
            ],
        ),
        (
            {
                "name": "大象机器人",
                "name_en": "Elephant Robotics",
                "country": "中国",
                "country_code": "CN",
                "website_url": "https://www.elephantrobotics.com",
                "description": None,
            },
            [
                {
                    "name": "myCobot 280",
                    "name_en": "myCobot 280",
                    "description": "大象机器人六轴协作机械臂，有效载荷 250g，工作半径 280mm，全球最轻量桌面协作臂，适用于教育",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "协作机器人",
                    "category_en": "Collaborative Robot",
                    "price_range": "low",
                    "status": "active",
                },
                {
                    "name": "myAGV",
                    "name_en": "myAGV",
                    "description": "大象机器人小型 AGV 移动平台，可搭载 myCobot 机械臂，构建移动操作机器人，适用于教学与研究",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "移动机器人",
                    "category_en": "Mobile Robot",
                    "price_range": "low",
                    "status": "active",
                },
            ],
        ),
        # ── 服务机器人 ────────────────────────────────────────────
        (
            {
                "name": "普渡科技",
                "name_en": "Pudu Robotics",
                "country": "中国",
                "country_code": "CN",
                "website_url": "https://www.pudurobotics.com",
                "description": None,
            },
            [
                {
                    "name": "BellaBot",
                    "name_en": "BellaBot",
                    "description": "普渡科技送餐机器人，仿猫咪外形，多层托盘配送，支持情感互动，已在全球 60+ 国家部署",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "服务机器人",
                    "category_en": "Service Robot",
                    "price_range": "medium",
                    "status": "active",
                },
                {
                    "name": "HolaBot",
                    "name_en": "HolaBot",
                    "description": "普渡科技大载量送餐机器人，可承载 60kg，适用于大型餐厅与食堂的高效配送",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "服务机器人",
                    "category_en": "Service Robot",
                    "price_range": "medium",
                    "status": "active",
                },
                {
                    "name": "KettyBot",
                    "name_en": "KettyBot",
                    "description": "普渡科技迎宾导引机器人，搭载广告屏，支持迎宾、配送与广告展示一体化",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "服务机器人",
                    "category_en": "Service Robot",
                    "price_range": "medium",
                    "status": "active",
                },
                {
                    "name": "FlashBot",
                    "name_en": "FlashBot",
                    "description": "普渡科技高速商用配送机器人，最高移动速度 2m/s，适用于酒店、医院与商场楼层间配送",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "服务机器人",
                    "category_en": "Service Robot",
                    "price_range": "medium",
                    "status": "active",
                },
            ],
        ),
        (
            {
                "name": "擎朗智能",
                "name_en": "Keenon Robotics",
                "country": "中国",
                "country_code": "CN",
                "website_url": "https://www.keenon.com",
                "description": None,
            },
            [
                {
                    "name": "T9",
                    "name_en": "Keenon T9",
                    "description": "擎朗智能送餐机器人，四层托盘，精准导航，已在全球数千家餐厅部署运营",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "服务机器人",
                    "category_en": "Service Robot",
                    "price_range": "medium",
                    "status": "active",
                },
                {
                    "name": "W3",
                    "name_en": "Keenon W3",
                    "description": "擎朗智能迎宾配送机器人，搭载 10.1 寸交互屏，支持语音交互与自主导航配送",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "服务机器人",
                    "category_en": "Service Robot",
                    "price_range": "medium",
                    "status": "active",
                },
                {
                    "name": "DINERBOT T5",
                    "name_en": "Keenon DINERBOT T5",
                    "description": "擎朗智能紧凑型餐厅服务机器人，适用于小面积餐厅，灵活导航无需改造场地",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "服务机器人",
                    "category_en": "Service Robot",
                    "price_range": "low",
                    "status": "active",
                },
            ],
        ),
        (
            {
                "name": "Bear Robotics",
                "name_en": "Bear Robotics",
                "country": "美国",
                "country_code": "US",
                "website_url": "https://bearrobotics.ai",
                "description": None,
            },
            [
                {
                    "name": "Servi",
                    "name_en": "Servi",
                    "description": "Bear Robotics 餐厅服务机器人，自主导航配送，已在全球 3000+ 餐厅部署",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "服务机器人",
                    "category_en": "Service Robot",
                    "price_range": "medium",
                    "status": "active",
                },
                {
                    "name": "Servi Plus",
                    "name_en": "Servi Plus",
                    "description": "Bear Robotics 升级版服务机器人，更大载量与更强导航能力，支持高峰时段密集服务",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "服务机器人",
                    "category_en": "Service Robot",
                    "price_range": "medium",
                    "status": "active",
                },
            ],
        ),
        # ── 移动机器人 ────────────────────────────────────────────
        (
            {
                "name": "MiR (Mobile Industrial Robots)",
                "name_en": "Mobile Industrial Robots",
                "country": "丹麦",
                "country_code": "DK",
                "website_url": "https://www.mobile-industrial-robots.com",
                "description": None,
            },
            [
                {
                    "name": "MiR100",
                    "name_en": "MiR100",
                    "description": "MiR 自主移动机器人，载重 100kg，自动规划路径，适用于工厂内部物料配送",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "移动机器人",
                    "category_en": "Mobile Robot",
                    "price_range": "high",
                    "status": "active",
                },
                {
                    "name": "MiR250",
                    "name_en": "MiR250",
                    "description": "MiR 高速自主移动机器人，载重 250kg，速度 2m/s，搭载先进安全系统",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "移动机器人",
                    "category_en": "Mobile Robot",
                    "price_range": "high",
                    "status": "active",
                },
                {
                    "name": "MiR600",
                    "name_en": "MiR600",
                    "description": "MiR 重型自主移动机器人，载重 600kg，适用于重型零部件的车间内自动化运输",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "移动机器人",
                    "category_en": "Mobile Robot",
                    "price_range": "high",
                    "status": "active",
                },
            ],
        ),
        (
            {
                "name": "松灵机器人",
                "name_en": "AgileX Robotics",
                "country": "中国",
                "country_code": "CN",
                "website_url": "https://www.agilex.ai",
                "description": None,
            },
            [
                {
                    "name": "Hunter SE",
                    "name_en": "AgileX Hunter SE",
                    "description": "松灵四轮差速移动机器人，最高速度 1.5m/s，适用于室外巡检与科研平台",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "移动机器人",
                    "category_en": "Mobile Robot",
                    "price_range": "medium",
                    "status": "active",
                },
                {
                    "name": "Scout 2.0",
                    "name_en": "AgileX Scout 2.0",
                    "description": "松灵四轮驱动移动机器人平台，负载 50kg，适用于室内外机器人研究与开发",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "移动机器人",
                    "category_en": "Mobile Robot",
                    "price_range": "medium",
                    "status": "active",
                },
                {
                    "name": "Bunker",
                    "name_en": "AgileX Bunker",
                    "description": "松灵履带式移动机器人，适用于复杂地形与野外环境的巡检与侦察任务",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "移动机器人",
                    "category_en": "Mobile Robot",
                    "price_range": "medium",
                    "status": "active",
                },
                {
                    "name": "LIMO Pro",
                    "name_en": "AgileX LIMO Pro",
                    "description": "松灵多模态教育机器人，支持四轮差速、阿克曼、履带三种运动模式，内置 ROS 开发环境",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "教育机器人",
                    "category_en": "Educational Robot",
                    "price_range": "low",
                    "status": "active",
                },
            ],
        ),
        (
            {
                "name": "Clearpath Robotics",
                "name_en": "Clearpath Robotics",
                "country": "加拿大",
                "country_code": "CA",
                "website_url": "https://clearpathrobotics.com",
                "description": None,
            },
            [
                {
                    "name": "Husky UGV",
                    "name_en": "Clearpath Husky UGV",
                    "description": "Clearpath 室外移动机器人平台，四轮驱动，承载 75kg，适用于野外科研与环境监测",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "移动机器人",
                    "category_en": "Mobile Robot",
                    "price_range": "high",
                    "status": "active",
                },
                {
                    "name": "Jackal UGV",
                    "name_en": "Clearpath Jackal UGV",
                    "description": "Clearpath 小型室外移动机器人，重量 17kg，速度 2m/s，适用于快速原型开发与野外巡逻",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "移动机器人",
                    "category_en": "Mobile Robot",
                    "price_range": "medium",
                    "status": "active",
                },
                {
                    "name": "Ridgeback",
                    "name_en": "Clearpath Ridgeback",
                    "description": "Clearpath 全向移动机器人平台，适用于大型机械臂的移动协作底盘",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "移动机器人",
                    "category_en": "Mobile Robot",
                    "price_range": "high",
                    "status": "active",
                },
            ],
        ),
        # ── 仓储物流 ──────────────────────────────────────────────
        (
            {
                "name": "Locus Robotics",
                "name_en": "Locus Robotics",
                "country": "美国",
                "country_code": "US",
                "website_url": "https://locusrobotics.com",
                "description": None,
            },
            [
                {
                    "name": "LocusBot Origin",
                    "name_en": "LocusBot Origin",
                    "description": "Locus Robotics 仓储协作机器人，与人工拣选员协作，已在全球 250+ 仓库部署，效率提升 2-3 倍",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "物流机器人",
                    "category_en": "Logistics Robot",
                    "price_range": "high",
                    "status": "active",
                }
            ],
        ),
        (
            {
                "name": "Fetch Robotics",
                "name_en": "Fetch Robotics",
                "country": "美国",
                "country_code": "US",
                "website_url": "https://fetchrobotics.com",
                "description": None,
            },
            [
                {
                    "name": "Freight 500",
                    "name_en": "Fetch Freight 500",
                    "description": "Fetch Robotics 自主移动运输机器人，载重 500kg，适用于仓储与工厂内大型货物搬运",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "物流机器人",
                    "category_en": "Logistics Robot",
                    "price_range": "high",
                    "status": "active",
                },
                {
                    "name": "Fetch",
                    "name_en": "Fetch",
                    "description": "Fetch Robotics 移动操作机器人，集成七轴机械臂与 AMR 底盘，可自主完成货架拣选任务",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "物流机器人",
                    "category_en": "Logistics Robot",
                    "price_range": "high",
                    "status": "active",
                },
            ],
        ),
        (
            {
                "name": "Simbe Robotics",
                "name_en": "Simbe Robotics",
                "country": "美国",
                "country_code": "US",
                "website_url": "https://www.simberobotics.com",
                "description": None,
            },
            [
                {
                    "name": "Tally",
                    "name_en": "Simbe Tally",
                    "description": "Simbe 零售货架巡检机器人，自动扫描货架缺货与错位，帮助零售商实时掌握库存状态",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "零售机器人",
                    "category_en": "Retail Robot",
                    "price_range": "high",
                    "status": "active",
                }
            ],
        ),
        # ── 社交 / 娱乐 ───────────────────────────────────────────
        (
            {
                "name": "Hanson Robotics",
                "name_en": "Hanson Robotics",
                "country": "中国香港",
                "country_code": "HK",
                "website_url": "https://www.hansonrobotics.com",
                "description": None,
            },
            [
                {
                    "name": "Sophia",
                    "name_en": "Sophia",
                    "description": "全球最著名的社交人形机器人，面部表情丰富，已获沙特公民身份，媒体与商业活动广泛亮相",
                    "cover_image_url_raw": None,
                    "video_urls": ["https://www.youtube.com/watch?v=78_Sd1PiAA4"],
                    "category": "社交机器人",
                    "category_en": "Social Robot",
                    "price_range": "inquiry",
                    "status": "active",
                },
                {
                    "name": "Little Sophia",
                    "name_en": "Little Sophia",
                    "description": "汉森机器人教育版 Sophia，身高 35cm，面向 K-12 教育市场，支持 Python、Scratch 编程",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "教育机器人",
                    "category_en": "Educational Robot",
                    "price_range": "medium",
                    "status": "active",
                },
            ],
        ),
        (
            {
                "name": "Engineered Arts",
                "name_en": "Engineered Arts",
                "country": "英国",
                "country_code": "GB",
                "website_url": "https://www.engineeredarts.co.uk",
                "description": None,
            },
            [
                {
                    "name": "Ameca",
                    "name_en": "Ameca",
                    "description": "全球表情最逼真的人形机器人，面部 17 个自由度，可实时生成 AI 驱动的对话与表情",
                    "cover_image_url_raw": None,
                    "video_urls": ["https://www.youtube.com/watch?v=IPukuYb9xWw"],
                    "category": "社交机器人",
                    "category_en": "Social Robot",
                    "price_range": "inquiry",
                    "status": "active",
                },
                {
                    "name": "Mesmer",
                    "name_en": "Mesmer",
                    "description": "Engineered Arts 仿真人机器人，外形与人类几乎无法区分，用于主题公园与科学展览",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "社交机器人",
                    "category_en": "Social Robot",
                    "price_range": "inquiry",
                    "status": "active",
                },
            ],
        ),
        (
            {
                "name": "Digital Dream Labs",
                "name_en": "Digital Dream Labs",
                "country": "美国",
                "country_code": "US",
                "website_url": "https://www.digitaldreamlabs.com",
                "description": None,
            },
            [
                {
                    "name": "Vector",
                    "name_en": "Vector",
                    "description": "家庭桌面宠物机器人，具备自主意识与情感表达，可通过语音和触摸交互，内置 AI 与云连接",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "娱乐机器人",
                    "category_en": "Entertainment Robot",
                    "price_range": "low",
                    "status": "active",
                },
                {
                    "name": "Cozmo",
                    "name_en": "Cozmo",
                    "description": "儿童教育娱乐机器人，个性鲜明，支持 Python SDK 编程，具备人脸识别与游戏互动功能",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "娱乐机器人",
                    "category_en": "Entertainment Robot",
                    "price_range": "low",
                    "status": "active",
                },
            ],
        ),
        # ── 中国四足 ──────────────────────────────────────────────
        (
            {
                "name": "深势科技 DeepRobotics",
                "name_en": "DeepRobotics",
                "country": "中国",
                "country_code": "CN",
                "website_url": "https://www.deeprobotics.cn",
                "description": None,
            },
            [
                {
                    "name": "Lite3",
                    "name_en": "DeepRobotics Lite3",
                    "description": "深势科技轻量级四足机器人，重量 10kg，最高速度 3.5m/s，适用于科研、教育与室外巡检",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "四足机器人",
                    "category_en": "Quadruped Robot",
                    "price_range": "medium",
                    "status": "active",
                },
                {
                    "name": "X30",
                    "name_en": "DeepRobotics X30",
                    "description": "深势科技工业级四足机器人，负载 10kg，具备多地形适应能力，适用于电力与矿山巡检",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "四足机器人",
                    "category_en": "Quadruped Robot",
                    "price_range": "high",
                    "status": "active",
                },
            ],
        ),
        # ── 医疗机器人 ────────────────────────────────────────────
        (
            {
                "name": "Intuitive Surgical",
                "name_en": "Intuitive Surgical",
                "country": "美国",
                "country_code": "US",
                "website_url": "https://www.intuitive.com",
                "description": None,
            },
            [
                {
                    "name": "Da Vinci Xi",
                    "name_en": "Da Vinci Xi",
                    "description": "全球最广泛使用的手术机器人系统，已完成超 1000 万台微创手术，覆盖普外、泌尿与妇科等领域",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "医疗机器人",
                    "category_en": "Medical Robot",
                    "price_range": "inquiry",
                    "status": "active",
                },
                {
                    "name": "Da Vinci SP",
                    "name_en": "Da Vinci SP",
                    "description": "Intuitive Surgical 单孔手术机器人，通过单一 25mm 切口完成多角度精细手术",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "医疗机器人",
                    "category_en": "Medical Robot",
                    "price_range": "inquiry",
                    "status": "active",
                },
                {
                    "name": "Ion",
                    "name_en": "Intuitive Ion",
                    "description": "Intuitive Surgical 肺部活检机器人，超细柔性导管，可到达肺部深处病灶进行精准活检",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "医疗机器人",
                    "category_en": "Medical Robot",
                    "price_range": "inquiry",
                    "status": "active",
                },
            ],
        ),
        (
            {
                "name": "Stryker",
                "name_en": "Stryker",
                "country": "美国",
                "country_code": "US",
                "website_url": "https://www.stryker.com",
                "description": None,
            },
            [
                {
                    "name": "Mako",
                    "name_en": "Stryker Mako",
                    "description": "史赛克骨科手术机器人，CT 三维规划 + 机械臂辅助切骨，精准度超传统手术，适用于膝髋关节置换",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "医疗机器人",
                    "category_en": "Medical Robot",
                    "price_range": "inquiry",
                    "status": "active",
                }
            ],
        ),
        # ── 农业机器人 ─────────────────────────────────────────────
        (
            {
                "name": "Naïo Technologies",
                "name_en": "Naïo Technologies",
                "country": "法国",
                "country_code": "FR",
                "website_url": "https://www.naio-technologies.com",
                "description": None,
            },
            [
                {
                    "name": "Oz",
                    "name_en": "Naïo Oz",
                    "description": "小型农业除草机器人，适用于蔬菜种植，自主导航穿行作物行间，减少 90% 除草人工",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "农业机器人",
                    "category_en": "Agricultural Robot",
                    "price_range": "high",
                    "status": "active",
                },
                {
                    "name": "Ted",
                    "name_en": "Naïo Ted",
                    "description": "Naïo 葡萄园除草机器人，适合葡萄种植园中的机械化除草作业，精准行驶于窄行距间",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "农业机器人",
                    "category_en": "Agricultural Robot",
                    "price_range": "high",
                    "status": "active",
                },
            ],
        ),
        (
            {
                "name": "Aethon",
                "name_en": "Aethon",
                "country": "美国",
                "country_code": "US",
                "website_url": "https://www.aethon.com",
                "description": None,
            },
            [
                {
                    "name": "TUG",
                    "name_en": "Aethon TUG",
                    "description": "医院自主物流机器人，自动运送药品、餐食与医疗用品，已在全球 200+ 家医院部署",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "服务机器人",
                    "category_en": "Service Robot",
                    "price_range": "high",
                    "status": "active",
                }
            ],
        ),
        (
            {
                "name": "Promobot",
                "name_en": "Promobot",
                "country": "俄罗斯",
                "country_code": "RU",
                "website_url": "https://promo-bot.ai",
                "description": None,
            },
            [
                {
                    "name": "Promobot V4",
                    "name_en": "Promobot V4",
                    "description": "商用服务机器人，自主导航，支持人脸识别与多语言对话，部署于银行、机场与展览中心",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "服务机器人",
                    "category_en": "Service Robot",
                    "price_range": "high",
                    "status": "active",
                },
                {
                    "name": "Promobot Robo-C",
                    "name_en": "Promobot Robo-C",
                    "description": "定制仿真人机器人，可定制成任意真实人物外形，用于商业接待、新闻播报等高关注度场景",
                    "cover_image_url_raw": None,
                    "video_urls": [],
                    "category": "社交机器人",
                    "category_en": "Social Robot",
                    "price_range": "inquiry",
                    "status": "active",
                },
            ],
        ),
    ]

    def crawl(self) -> list[dict]:
        # 此爬虫不爬网络，直接返回空，主入口单独处理 SEED_DATA
        return []
